### PR TITLE
Fix RX mode for ATtiny84

### PR DESCRIPTION
**Pull request by nighthawk6389**
Tested on ATtiny84 8Mhz with Arduino 1.6.

TCCR1A needs to be set to 0 BEFORE setting TCCR1B. Otherwise OCR1A isn't respected.

### CODE REVIEW

**Comment by mchr3k** [comment]
Can you please resolve the conflict and then I'll accept your change? I really appreciate the contribution :)

**Comment by nighthawk6389** [comment]
Merges should be resolved now.

**Comment by mchr3k** [comment]
Oh no :( It looks like you still conflict with https://github.com/mchr3k/arduino-libs-manchester/pull/28 which I just pulled in. Can you fix again? I'm really sorry!

**Comment by nighthawk6389** [comment]
Better late than never I guess....fixed the merge conflict :)

**Comment by mchr3k** [comment]
Thanks!

**Pull request merged**
